[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "https://rattecs.com/*"
to = "https://ratte.seweraim.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://ratte.seweraim.com/*"
to = "https://ratte.seweraim.com/:splat"
status = 301
force = true

[headers]
# Security headers
[[headers.headers]]
key = "X-Frame-Options"
value = "SAMEORIGIN"

[[headers.headers]]
key = "X-Content-Type-Options"
value = "nosniff"

[[headers.headers]]
key = "Referrer-Policy"
value = "strict-origin-when-cross-origin"

# SEO headers
[[headers.headers]]
key = "Cache-Control"
value = "public, max-age=3600, s-maxage=86400"

[[headers.headers]]
key = "Link"
value = "</sitemap.xml>; rel=\"sitemap\"; type=\"application/xml\""

# Performance headers
[[headers.headers]]
key = "Strict-Transport-Security"
value = "max-age=31536000; includeSubDomains; preload"

[[headers.headers]]
key = "Permissions-Policy"
value = "interest-cohort=()" 